### ISSUE TITLE
Getting 403 for all calls to draw.json

### ISSUE THREAD

**Issue by devedse** [Zequez/reddit-placebot#11]
I just created a new throwaway account but have been getting only 403 errors:

![image](https://cloud.githubusercontent.com/assets/2350015/24588592/6dbb9ba6-17cb-11e7-86ee-bc2f30ec0ed6.png)

I also seem to get them when doing it from the browser:

![image](https://cloud.githubusercontent.com/assets/2350015/24588582/33ef38b0-17cb-11e7-9b7b-84b255429ff6.png)

Any clue what could be going on here?

**Comment by RobinFlikkema** [comment]
Is this a newly created account? I'm having the same issue when using new accounts. If i use accounts which i've had for months it works fine

**Comment by devedse** [comment]
Yeah it's a new account

**Comment by RobinFlikkema** [comment]
It might be some reddit policy as i'm also getting a 403 when using a newly created account on https://www.reddit.com/r/place/

**Comment by xXFlorianXx** [comment]
Check the rules on https://www.reddit.com/r/place/:
**Only accounts created before 31-03-2017 may place tiles**

**Comment by devedse** [comment]
Aha :), makes sense. Kinda stupid reddit doesn't give good visual feedback to the user about this though.
