### ISSUE TITLE
Doesn't work (bit decode error:RangeError: Index out of range)

### ISSUE THREAD

**Issue by christopher-c-c** [Zequez/reddit-placebot#12]
target.bmp = https://a.safe.moe/eJGYK.bmp 

`└── npm run start`

`> reddit-placebot@1.0.0 start /home/christopher/reddit-placebot`
`> node run.js`

`xxxxxxxxxxxxxx -154s; xxxxxxxxx -154s; xxxxxxxxxxxxx -154s; xxxxxxxxxxxxxx -154s`
`Running user  xxxxxxxxxxxxxxx`
`bit decode error:RangeError: Index out of range`
`(node:30456) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1):` `Invalid color at X: 0 Y: 0`

**Comment by Lenni** [comment]
I wont support you posting Nazi Symbols!

**Comment by christopher-c-c** [comment]
>The Swastika (also known outside the Indian subcontinent as the Hakenkreuz, gammadion cross, cross cramponnée, croix gammée, fylfot, or tetraskelion) (as a character 卐 or 卍) is an ancient religious symbol originating from the Indian subcontinent, that generally takes the form of an equilateral cross with four legs each bent at 90 degrees.[1][2] It is considered to be a sacred and auspicious symbol in Hinduism, Buddhism, and Jainism and dates back at least 11,000 years.[3]

**Comment by christopher-c-c** [comment]
i spread peace I promise

**Comment by Lenni** [comment]
Well, doesnt matter in Germany

**Comment by TheJuiceDidThis** [comment]
I support your usage of this sigil by rights of Kek. Kekistani rights must be preserved even when other nation-states would censor your expression!

**Comment by Lenni** [comment]
Okay okay....
Your Image needs to be 1000x1000 Pixels, it would be besteht, if you download the official-target.BMP and edit it for your purpose

**Comment by christopher-c-c** [comment]
@Lenni I used imagemagick to make it 1000x1000 but I am still receiving this error (the others went away):

`(node:10333) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Invalid color at X: 0 Y: 0`

**Comment by Zequez** [comment]
Make sure it meets the following requirements:

- Format: BMP
- Dimensions: 1000x1000
- Compression: NONE! Should weight about 3mb, 4 bytes per color
- Colors: exactly the same colors used in the board
- Transparency: Color #ff00ffff is considered transparent (a bright purple color), and will be ignored by the bots

Also, try to use the [images/target.example.bmp](https://github.com/Zequez/reddit-placebot/raw/master/images/target.example.bmp) file and start from there.

**Comment by Zequez** [comment]
Now the app support any kind of file (PNG, JPG or BMP) and any kind of colors (will do color matching), and it allows you to set the target starting position so you can use small images as target. So please update :P d5933e7 4d6961d 7f9fcd0
