### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Invalid BMP File

### ISSUE THREAD

**Issue by Spookzy** [Zequez/reddit-placebot#13]
apon attempting to run the bot I receive this error
`UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Invalid BMP File`
despite having the bot setup correctly with a correct BMP file.
unless my bmp isn't correct.
I can send it for reference if required but i'm pretty sure it's correct

**Comment by Lenni** [comment]
Try to create the BMP in Windows Paint with only the colors referenced in the colors.json

**Comment by ololizoz** [comment]
Yeah, I have the same problem. I'm pretty sure mp BMP is correct, it couldn't be another issue?

**Comment by Lenni** [comment]
Can you upload your BMP somewhere, so I can check?

**Comment by ololizoz** [comment]
This is mine: [https://drive.google.com/file/d/0B8OapVHZ0_BsdGc1eXR6bUFxRk0/view?usp=sharing](url)

**Comment by Lenni** [comment]
You habe to usw a 1000x1000 Version of the Image. The Areal oft the board which shouldnt be painted you can color with 255 0 255

**Comment by Spookzy** [comment]
the colors are correct with the reference in colors.json and still has the same error

**Comment by Spookzy** [comment]
https://puu.sh/v71PD/b767cd0120.bmp
This is my BMP
Is this right?

**Comment by Lenni** [comment]
Yes

**Comment by Spookzy** [comment]
then I have no idea why it doesn't work

**Comment by Lenni** [comment]
Try to create it in Paint. I noticed, that the image was heavily compressed. It took only 7KB of space. It should be more like ~3MB

**Comment by Spookzy** [comment]
hmmm ok
thanks

**Comment by Zequez** [comment]
I just updated the Readme with all the requirements for the target file, could you check that everything meets the requirements? Also, I added a target.example.bmp and a board.example.bmp, you could try to modify them instead of creating it from scratch.

**Comment by Zequez** [comment]
Now the app support any kind of file (PNG, JPG or BMP) and any kind of colors (will do color matching), and it allows you to set the target starting position so you can use small images as target. So please update :P d5933e7a9c7caeabd7fb9c00c2ce489bf97ff2f8 4d6961d965c564e9e908adcafacbd25a63c1454f 7f9fcd01f412ff4b6b2a4dec93f4260304e45aa5
