### ISSUE TITLE
Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'modhash' of undefined

### ISSUE THREAD

**Issue by ololizoz** [Zequez/reddit-placebot#14]
Getting this error. What should I do?

Link to BMP: https://drive.google.com/file/d/0B8OapVHZ0_BsblQwaXk0amc4SFU/view?usp=sharing

**Comment by Rezonation** [comment]
Your username or password is wrong

**Comment by ololizoz** [comment]
Yeah, thanks!

I re-installed everything and I setup the users.json file before I ran "npm install", that fixed it.
