### ISSUE TITLE
Getting an invalid color at 232,0

### ISSUE THREAD

**Issue by Doctah** [Zequez/reddit-placebot#15]
This is basically where the "transparency" portion of the image starts for me.

The image *is* 1000x1000, saved as a 24-bit BMP through GIMP (do not have Windows, so no paint here) and all colors are valid within the painted area. This seems to make the script only paint in 0,0. Any ideas? I had someone 're-save' my BMP and the result is still the same. Though I did notice that the color in `board_differ.js` is `0xff00fff`, with an extra F. Is that intentional?

**Comment by Zequez** [comment]
It's supposed to be RGBA 4 bytes per color, but the A portion isn't used and the color should be exactly: `0xff00ffff`

**Comment by Zequez** [comment]
Now the app support any kind of file, including PNG, and less than 1000x1000 pixels files (you have to set the start position). d5933e7a9c7caeabd7fb9c00c2ce489bf97ff2f8
