### ISSUE TITLE
Having multiple accounts causes them to place the same pixel at the same time

### ISSUE THREAD

**Issue by xpopy** [Zequez/reddit-placebot#18]
Acc1 -333s; Acc2-332s
Running user  Acc1 
Painting  { x: 47, y: 756, color: 0 }
Queue saved!
Acc1 300s; Acc2-338s
Running user  Acc2
Painting  { x: 47, y: 756, color: 0 }
Queue saved!

**Comment by Zequez** [comment]
I'm not sure what caused this in the past, but make sure you're running the latest version and read the updated readme, there were a lot of changes in the last 7 hours.
