### ISSUE TITLE
Display Time of action

### ISSUE THREAD

**Issue by frenchiveruti** [Zequez/reddit-placebot#19]
Right now the bot logs the remaining time for the next pixel imput, but it doesn't state when it made that last check, it would be a nice addition so we can know if the bot got stuck or something.

So:
HH:MM 'username' ###s

**Comment by Zequez** [comment]
Good idea, I just improved the logging of the queues, now it says:

`Next account in XXX seconds, at HH:MM`

And it doesn't log anything else until then.
