### ISSUE TITLE
Not running on Debian

### ISSUE THREAD

**Issue by Lenni** [Zequez/reddit-placebot#2]
When I try to run the bot i get the following error: 

npm ERR! reddit-placebot@1.0.0 start: `nodejs run.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the reddit-placebot@1.0.0 start script.
npm ERR! This is most likely a problem with the reddit-placebot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nodejs run.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls reddit-placebot
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.32-openvz-042stab113.11-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
npm ERR! cwd /root/reddit-placebot-master
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/reddit-placebot-master/npm-debug.log
npm ERR! not ok code 0

**Comment by Zequez** [comment]
I'm not with my computer right now, but try to run it with the latest  version of node.

**Comment by Chibears85** [comment]
I also tried to run it on Debian, I have node installed (latest version) but I get the same error as above.  What's a different way i can run this to have it work?

**Comment by dotcade** [comment]
@Zequez I get the same error on Windows.

**Comment by RobinFlikkema** [comment]
Please post the output of the npm-debug.log

**Comment by Megalan** [comment]
I have no problems running it on Debian but I had to install latest nodejs with

> curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -
sudo apt-get install -y nodejs

**Comment by Lenni** [comment]
Did that, but now ist says that there is an issue at "throw error"

**Comment by Lenni** [comment]
Error Message:

module.js:472
    throw err;
    ^

Error: Cannot find module './users'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/reddit-placebot-master/run.js:15:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by Megalan** [comment]
Have you followed installation and configuration instructions? Looks like you have missed some steps.

**Comment by Lenni** [comment]
Okay, reinstalled it and now it works like a charm
