### ISSUE TITLE
Last commit killed the script

### ISSUE THREAD

**Issue by daphee** [Zequez/reddit-placebot#21]
In the userPaint function you uncommented the three lines 88, 89, 90 (mock painting). Now the function returns before being able to send the HTTP request.

**Comment by wilsonbiggs** [comment]
I can confirm this. It can be fixed by commenting out those three lines manually.

**Comment by Zequez** [comment]
Oh sorry! I just made a big refactoring, now the mock painting is a configuration option, try updating again!

**Comment by jayrandez** [comment]
Thank you person who posted this issue...

**Comment by cjwelborn** [comment]
Hah, it took me a minute to figure that out by the console output (`"Mock Painting"`). One look at the script and I thought "was this on purpose? :confused:" `Ctrl + /` to the rescue.
