### ISSUE TITLE
Properly handle negative index bitmaps

### ISSUE THREAD

**Issue by mlindner** [Zequez/reddit-placebot#24]
Negative index bitmaps are standard across Mac OS X and it's impossible to generate positive index bitmaps as far as I can tell. These filetypes should be supported.

**Comment by Zequez** [comment]
I think the ideal would be to use the Jimp library (which we currently just use in the generation of the BMP file when downloading the bitmap from Reddit) to just read any file format and use `getPixelColor` and then try to find the closest color match for the color, to support compressed images.

**Comment by Zequez** [comment]
Also, is probably not worth it considering /r/place is going to close soon.

**Comment by Zequez** [comment]
This was fixed, probably with the latest updates that allow to use any kind of file for the target. d5933e7a9c7caeabd7fb9c00c2ce489bf97ff2f8
