### ISSUE TITLE
fs.js:641   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);                  ^  Error: ENOENT: no such file or directory, open '/Users/champtoday/reddit-placebot/src/../tmp/cookies.json'

### ISSUE THREAD

**Issue by nrgapple** [Zequez/reddit-placebot#28]

**Comment by cjwelborn** [comment]
@nrgapple I think this was fixed already. A workaround is to create a file called `tmp/cookies.json` in the repo's root directory, but I would try the latest version (`git pull` and restart).

**Comment by nrgapple** [comment]
thanks for the quick response! will pull now

**Comment by nrgapple** [comment]
worked. I'm getting "YourRedditUserName -1.003s; OtherAccount -1.002s; MoreThrowaways -1.002s
Next account in Infinity seconds, at NaN:NaN
3/4 accounts until update"

**Comment by cjwelborn** [comment]
@nrgapple, you need to edit or create `users.json` before running it. It should have:
```
{
    "YOUR_REDDIT_NAME": "YOUR_REDDIT_PASSWORD"
}
```
..You can add more accounts if needed:
```
{
    "YOUR_REDDIT_NAME": "YOUR_REDDIT_PASSWORD",
    "YOUR_OTHER_ACCOUNT": "YOUR_OTHER_ACCOUNT's PASSWORD"
}
```

The `users.example.json` file is just what it says, an example of configuring reddit accounts for the bot.
You also need to edit `config.js` to point `REMOTE_TARGET_URL` to the correct target image, if you haven't already.

**Comment by Zequez** [comment]
You have to edit the `bundleAccounts: X` configuration file with the number of accounts you want to bundle. I'll make a change so it automatically caps at the number of accounts available.
