### ISSUE TITLE
Old version drew right to left, up to down. New version draws at random.

### ISSUE THREAD

**Issue by Chibears85** [Zequez/reddit-placebot#30]
The old version drew left to right, up to down. It made it a lot easier for it to correct itself while it drew itself. This newest version is just putting things everywhere at random. Is there a way to incorporate it back to not random?

**Comment by Zequez** [comment]
I'll add an option to configure this.

**Comment by Chibears85** [comment]
The new option goes left to right then up to down. The reverse of what it used to be of up to down then left to right.
