### ISSUE TITLE
Red Painting As Blue

### ISSUE THREAD

**Issue by Joshj5hawk** [Zequez/reddit-placebot#33]
I have color matched to get the Red from the tmp/board file and Red will continually paint as blue. My Red color code is 229 0 0 when I eye drop it (E50000) as is the same when going from the board

**Comment by Joshj5hawk** [comment]
Looks like trying to place yellow places Cyan also.

**Comment by Joshj5hawk** [comment]
Turns out that drawing blue will output red, and drawing cyan will output yellow.

**Comment by Zequez** [comment]
I've been trying to reproduce it but I couldn't yet. Could you provide me the image that is failing?

**Comment by Joshj5hawk** [comment]
Yepp, 100 percent sure. That and the fact that my image doesn't have any cyan or blue in it ;)
! [target](https://cloud.githubusercontent.com/assets/3804067/24606245/ea2bbc32-1831-11e7-88f2-add62ca321f5.png)

**Comment by Zequez** [comment]
Could you copy your config.js file here? Also, do you have the latest version?

**Comment by Joshj5hawk** [comment]
----------------------------------------------------
Here is my current config.js
----------------------------------------------------

module.exports = {
  BOARD_URL: 'https://www.reddit.com/api/place/board-bitmap',
  BOARD_FILE: __dirname + '/tmp/board.bmp',
  BOARD_H: 1000,
  BOARD_W: 1000,

  REMOTE_TARGET_URL: 'https://raw.githubusercontent.com/Zequez/placebot-argentina-target/master/official_target.bmp',
  REMOTE_TARGET_FILE: __dirname + '/tmp/target.bmp',

  LOCAL_TARGET_FILE: __dirname + '/images/target.bmp',

  DRAW_URL: 'https://www.reddit.com/api/place/draw.json',

  // Use the REMOTE_TARGET_URL file as target, otherwise it's gonna just
  // try to read from target.bmp
  autoupdateRemoteTarget: false,

  // Wait until these amount of accounts are available
  // and paint pixels at the same time
  bundleAccounts: 2,
  
  //Added Configs
  targetStartX: 957,
  targetStartY: 478,
  drawMode: 'RANDOM',

  // Do not send the painting to the server so you don't waste your pixels
  // while testing something else
  mockPainting: true //true for current color testing/debugging
}

----------------------------------------------------
Console Output
----------------------------------------------------

###############################################
######### CONFIGURATION (change on config.json)
  Using Local Target:  /home/joshj5hawk/reddit-placebot/images/target.bmp
  Accounts:  JoshJ5Hawk, RedditStreamBot, AngryGabbyBot, KuemperMooBot, CoachTorchettiBot, AngryYeoBot, WhyIsHeTheMilkmanBot, ahammsamich
  Bundle Accounts:  8
  Target Start Position:  X: 957  Y: 478
  Target Draw Mode: RANDOM
  Testing flag: mockPainting
###############################################
###############################################


Getting modhash and cookies for  JoshJ5Hawk
Getting modhash and cookies for  RedditStreamBot
Getting modhash and cookies for  AngryGabbyBot
Getting modhash and cookies for  KuemperMooBot
Getting modhash and cookies for  CoachTorchettiBot
Getting modhash and cookies for  AngryYeoBot
Getting modhash and cookies for  WhyIsHeTheMilkmanBot
Getting modhash and cookies for  ahammsamich
Running users  JoshJ5Hawk, RedditStreamBot, AngryGabbyBot, KuemperMooBot, CoachTorchettiBot, AngryYeoBot, WhyIsHeTheMilkmanBot, ahammsamich
Finding actions
Painting  { x: 983, y: 488, color: 13, name: 'blue' }
Mock painting!
Painting  { x: 987, y: 491, color: 13, name: 'blue' }
Mock painting!
Painting  { x: 981, y: 490, color: 13, name: 'blue' }
Mock painting!
Painting  { x: 965, y: 496, color: 13, name: 'blue' }
Mock painting!
Painting  { x: 996, y: 486, color: 13, name: 'blue' }
Mock painting!
Painting  { x: 987, y: 487, color: 13, name: 'blue' }
Mock painting!
Painting  { x: 991, y: 485, color: 13, name: 'blue' }
Mock painting!
Painting  { x: 987, y: 490, color: 13, name: 'blue' }
Mock painting!
JoshJ5Hawk 5s; RedditStreamBot 5s; AngryGabbyBot 5s; KuemperMooBot 5s; CoachTorchettiBot 5s; AngryYeoBot 5s; WhyIsHeTheMilkmanBot 5s; ahammsamich 5s
Next account in 5 seconds, at 8:42
0/8 accounts until update

----------------------------------------------------
Current Target File
----------------------------------------------------

http://i.imgur.com/sOTappq.png (target file is .bmp)

----------------------------------------------------
Version
----------------------------------------------------

Cloned from Git at 0839 April 3rd 2017

**Comment by Zequez** [comment]
Closing as /r/place ended.
