### ISSUE TITLE
error running script

### ISSUE THREAD

**Issue by Strygen** [Zequez/reddit-placebot#34]
Hi, i cant get the script to work, This is image of full cmd-log: https://gyazo.com/c970b054045167124473470324f471dc
And this is debug.log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@4.2.0
3 info using node@v7.8.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle reddit-placebot@1.1.0~prestart: reddit-placebot@1.1.0
6 silly lifecycle reddit-placebot@1.1.0~prestart: no script for prestart, continuing
7 info lifecycle reddit-placebot@1.1.0~start: reddit-placebot@1.1.0
8 verbose lifecycle reddit-placebot@1.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle reddit-placebot@1.1.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Henrik\Desktop\swedenplace\reddit-placebot-e8abb8aa8d82600f9fa7273c250de49028513e45\node_modules\.bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\MATLAB\R2013b\bin;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Users\Henrik\AppData\Local\Microsoft\WindowsApps;C:\Users\Henrik\AppData\Roaming\npm
10 verbose lifecycle reddit-placebot@1.1.0~start: CWD: C:\Users\Henrik\Desktop\swedenplace\reddit-placebot-e8abb8aa8d82600f9fa7273c250de49028513e45
11 silly lifecycle reddit-placebot@1.1.0~start: Args: [ '/d /s /c', 'node src/run.js --harmony' ]
12 silly lifecycle reddit-placebot@1.1.0~start: Returned: code: 1  signal: null
13 info lifecycle reddit-placebot@1.1.0~start: Failed to exec start script
14 verbose stack Error: reddit-placebot@1.1.0 start: `node src/run.js --harmony`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid reddit-placebot@1.1.0
16 verbose cwd C:\Users\Henrik\Desktop\swedenplace\reddit-placebot-e8abb8aa8d82600f9fa7273c250de49028513e45
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
19 error node v7.8.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error reddit-placebot@1.1.0 start: `node src/run.js --harmony`
23 error Exit status 1
24 error Failed at the reddit-placebot@1.1.0 start script 'node src/run.js --harmony'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the reddit-placebot package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     node src/run.js --harmony
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs reddit-placebot
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls reddit-placebot
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by Joshj5hawk** [comment]
Double check your line endings in your users config file, should look like this:

`{
  "USERNAME": "PASSWORD",
  "USERNAME": "PASSWORD",
  "USERNAME": "PASSWORD",
  "USERNAME": "PASSWORD",
  "USERNAME": "PASSWORD",
  "USERNAME": "PASSWORD",
  "USERNAME": "PASSWORD",
  "USERNAME": "PASSWORD"
}
`

**Comment by Strygen** [comment]
Thanks, i was only using it on a single account and still had a lead after "password"
