### ISSUE TITLE
password characters

### ISSUE THREAD

**Issue by granttmartin** [Zequez/reddit-placebot#36]
I was getting this error:
SyntaxError: /home/user/Software/reddit-placebot/users.json: Unexpected token   in JSON at position 59

Pretty sure it's because my password included a "\". The error went away after i generated a new password.

EDIT. The backslash isn't showing in my quotes here either. `\`

**Comment by Zequez** [comment]
You have to escape the `"` and `\` characters as `\"` and `\\` accordingly, otherwise is not gonna be a valid json file.
