### ISSUE TITLE
Invalid Colors for Red and Orange

### ISSUE THREAD

**Issue by nnN8THEGR8nn** [Zequez/reddit-placebot#4]
I've triple checked the exact color values but still get an invalid color error whenever it hits red or orange. There may be other colors it has issues with but these are the two I've run into.

**Comment by daphee** [comment]
Could you provide a sample bmp? No issues here with Red.

**Comment by Lenni** [comment]
No issues from here either. Can you provide you target bmp, so we can check?

**Comment by RobinFlikkema** [comment]
You need to use 229, 0, 0 for red

**Comment by Zequez** [comment]
Use the eyedropper tool on the board.example.bmp file.

**Comment by nnN8THEGR8nn** [comment]
I've tried every way to grab the color, including using the eyedropper tool. Here is what I've been using just to try and get it to work. I had to convert it to png to upload it here.
![target1](https://cloud.githubusercontent.com/assets/5498046/24592167/7e580948-17d7-11e7-809e-9669648a0bb3.png)

**Comment by Zequez** [comment]
What software are you using for editing the image?

**Comment by nnN8THEGR8nn** [comment]
I've tried both paint.net and ms paint.

**Comment by Zequez** [comment]
Could you zip the file and upload it here?

**Comment by nnN8THEGR8nn** [comment]
I figured it out. Both the programs were set to auto detect bit depth, which was setting it to 8-bit rather than 24-bit. Setting it to 24-bit manually has fixed it. Thanks for the help!

**Comment by Zequez** [comment]
Well, anyway, now the app support any kind of file (like compressed png), color matching (you can use any color and will find the closest) and starting position (you can use small targets). So this won't happen again. d5933e7 4d6961d 7f9fcd0
