### ISSUE TITLE
TypeError: Cannot read property 'modhash' of undefined

### ISSUE THREAD

**Issue by DankidyDan** [Zequez/reddit-placebot#6]
http://i.imgur.com/BMoYEJ9.png

I'll edit in my usernames, rename the .json, etc. as per the instructions, and I still get this after installing and running it.

I initially thought it had something to do with my modifications when trying to paint my own image, but it does the exact same thing even when I leave everything default (other than adding my usernames in users.json)

What gives?

**Comment by Lenni** [comment]
Remove the other accounts behind your account in the queues.json

**Comment by AngrySc0rpi0n** [comment]
Hmm, I did that and I am still getting the error. What else would be causing it?

**Comment by Lenni** [comment]
Can you close the issue then? :D

**Comment by AngrySc0rpi0n** [comment]
I can't close it, but OP can (avatars are a little deceiving)

**Comment by Chibears85** [comment]
I'm getting this same error and can not figure out how to fix it.

**Comment by Lenni** [comment]
Be sure to only habe your username and password in the users.json

**Comment by Chibears85** [comment]
All the usernams and passwords work on firefox and they are all only in the users.json but i still get the error

**Comment by Lenni** [comment]
Can you post the error message?

**Comment by Chibears85** [comment]
Figured out the issue was that I get the error when reddit servers don't respond which is happening a lot right now. Should be an option where it keeps re-trying on it's own so I don't have to keep re-starting it every time.

**Comment by Zequez** [comment]
Cool you guys could solve it, closing then.
